export const interfaceTasksBy143411 = {
  count: 6,
  next: null,
  previous: null,
  results: [
    {
      id: 42,
      interface: {
        id: 143411,
        code: 'UIO-00005-IF-CI',
      },
      created_by: {
        id: 3,
        username: 'pek',
        first_name: 'Pe',
        last_name: 'K',
        email: 'pek@pesco.energy',
      },
      updated_by: null,
      reviewers: [
        {
          id: 2887,
          name: 'PEKCO',
          company_code: 'PKC',
          participation_type: 'PMC',
        },
      ],
      answers: [],
      files: [
        {
          file: 'http://dcmsportal.pesco.energy/media/files/UIO-00005-IF-CI/registry_head_14.xlsx',
        },
      ],
      task_theme: 'test12',
      task_text: 'test',
      time_created: '2025-01-23T15:15:35.116267+03:00',
      time_modified: '2025-01-23T15:15:35.116291+03:00',
      due_date: '2025-01-07',
      status: 'open',
    },
    {
      id: 37,
      interface: {
        id: 143411,
        code: 'UIO-00005-IF-CI',
      },
      created_by: {
        id: 3,
        username: 'pek',
        first_name: 'Pe',
        last_name: 'K',
        email: 'pek@pesco.energy',
      },
      updated_by: null,
      reviewers: [
        {
          id: 2887,
          name: 'PEKCO',
          company_code: 'PKC',
          participation_type: 'PMC',
        },
      ],
      answers: [
        {
          id: 32,
          text: 'Write\nPreview\nfd',
          time_created: '2025-01-21T13:44:32.679464+03:00',
          task: 37,
          created_by: 3,
        },
        {
          id: 35,
          text: 'Write\nPreview\nfr',
          time_created: '2025-01-21T15:38:44.509003+03:00',
          task: 37,
          created_by: 3,
        },
        {
          id: 36,
          text: 'Write\nPreview\nfrrf',
          time_created: '2025-01-21T15:38:46.220747+03:00',
          task: 37,
          created_by: 3,
        },
        {
          id: 37,
          text: 'Write\nPreview\nfrrfrf',
          time_created: '2025-01-21T15:38:48.238695+03:00',
          task: 37,
          created_by: 3,
        },
        {
          id: 39,
          text: 'otkril',
          time_created: '2025-01-21T17:19:46.126837+03:00',
          task: 37,
          created_by: 3,
        },
        {
          id: 40,
          text: 'Write\nPreview',
          time_created: '2025-01-21T17:20:52.077840+03:00',
          task: 37,
          created_by: 3,
        },
        {
          id: 41,
          text: 'otkril',
          time_created: '2025-01-21T17:21:07.169875+03:00',
          task: 37,
          created_by: 3,
        },
        {
          id: 42,
          text: 'Write\nPreview',
          time_created: '2025-01-21T17:21:17.676867+03:00',
          task: 37,
          created_by: 3,
        },
        {
          id: 51,
          text: 'vdvdv',
          time_created: '2025-01-23T14:33:18.391114+03:00',
          task: 37,
          created_by: 3,
        },
      ],
      files: [
        {
          file: 'http://dcmsportal.pesco.energy/media/files/UIO-00005-IF-CI/registry_head_15_0HUSoOP.xlsx',
        },
      ],
      task_theme: 'Theme',
      task_text: 'Write\r\nPreview\r\nамас',
      time_created: '2025-01-21T13:40:30.135069+03:00',
      time_modified: '2025-01-23T12:07:18.175725+03:00',
      due_date: '2024-12-31',
      status: 'open',
    },
    {
      id: 36,
      interface: {
        id: 143411,
        code: 'UIO-00005-IF-CI',
      },
      created_by: {
        id: 3,
        username: 'pek',
        first_name: 'Pe',
        last_name: 'K',
        email: 'pek@pesco.energy',
      },
      updated_by: null,
      reviewers: [
        {
          id: 2887,
          name: 'PEKCO',
          company_code: 'PKC',
          participation_type: 'PMC',
        },
      ],
      answers: [
        {
          id: 34,
          text: 'Write\nPreview\nfhg',
          time_created: '2025-01-21T14:42:47.738122+03:00',
          task: 36,
          created_by: 3,
        },
        {
          id: 43,
          text: 'fgf',
          time_created: '2025-01-23T12:05:03.897224+03:00',
          task: 36,
          created_by: 3,
        },
        {
          id: 44,
          text: 'fgf',
          time_created: '2025-01-23T12:05:05.989720+03:00',
          task: 36,
          created_by: 3,
        },
        {
          id: 45,
          text: '@Timur PEKCO gb',
          time_created: '2025-01-23T12:07:36.033076+03:00',
          task: 36,
          created_by: 3,
        },
        {
          id: 46,
          text: '@Timur PEKCO gb',
          time_created: '2025-01-23T12:07:39.257846+03:00',
          task: 36,
          created_by: 3,
        },
        {
          id: 47,
          text: 'hfhgh',
          time_created: '2025-01-23T12:09:15.439719+03:00',
          task: 36,
          created_by: 3,
        },
        {
          id: 48,
          text: '@Timur PEKCO gb',
          time_created: '2025-01-23T12:09:19.695757+03:00',
          task: 36,
          created_by: 3,
        },
        {
          id: 49,
          text: 'rrrr',
          time_created: '2025-01-23T12:09:32.570864+03:00',
          task: 36,
          created_by: 3,
        },
        {
          id: 50,
          text: 'dvf',
          time_created: '2025-01-23T14:33:11.149382+03:00',
          task: 36,
          created_by: 3,
        },
      ],
      files: [
        {
          file: 'http://dcmsportal.pesco.energy/media/files/UIO-00005-IF-CI/registry_head_15_X8Zd1LK.xlsx',
        },
      ],
      task_theme: 'Theme',
      task_text: 'Write\r\nPreview\r\nаdа',
      time_created: '2025-01-21T13:31:08.449416+03:00',
      time_modified: '2025-01-23T14:33:11.142242+03:00',
      due_date: '2024-12-30',
      status: 'closed',
    },
    {
      id: 35,
      interface: {
        id: 143411,
        code: 'UIO-00005-IF-CI',
      },
      created_by: {
        id: 3,
        username: 'pek',
        first_name: 'Pe',
        last_name: 'K',
        email: 'pek@pesco.energy',
      },
      updated_by: null,
      reviewers: [
        {
          id: 2887,
          name: 'PEKCO',
          company_code: 'PKC',
          participation_type: 'PMC',
        },
      ],
      answers: [
        {
          id: 33,
          text: 'Write\nPreview\nf',
          time_created: '2025-01-21T14:41:35.745238+03:00',
          task: 35,
          created_by: 3,
        },
        {
          id: 38,
          text: 'Write\nPreview',
          time_created: '2025-01-21T17:09:43.556713+03:00',
          task: 35,
          created_by: 3,
        },
        {
          id: 52,
          text: '@Lyudmila PEKCO',
          time_created: '2025-01-23T14:45:18.947402+03:00',
          task: 35,
          created_by: 3,
        },
        {
          id: 53,
          text: 'dv',
          time_created: '2025-01-23T14:45:27.745834+03:00',
          task: 35,
          created_by: 3,
        },
      ],
      files: [
        {
          file: 'http://dcmsportal.pesco.energy/media/files/UIO-00005-IF-CI/registry_head_15_M6Icajs.xlsx',
        },
      ],
      task_theme: 'test',
      task_text: 'Write\r\nPreview\r\nfbf',
      time_created: '2025-01-21T09:25:59.215115+03:00',
      time_modified: '2025-01-23T14:45:23.743110+03:00',
      due_date: '2025-01-14',
      status: 'open',
    },
    {
      id: 32,
      interface: {
        id: 143411,
        code: 'UIO-00005-IF-CI',
      },
      created_by: {
        id: 3,
        username: 'pek',
        first_name: 'Pe',
        last_name: 'K',
        email: 'pek@pesco.energy',
      },
      updated_by: null,
      reviewers: [
        {
          id: 2887,
          name: 'PEKCO',
          company_code: 'PKC',
          participation_type: 'PMC',
        },
      ],
      answers: [],
      files: [
        {
          file: 'http://dcmsportal.pesco.energy/media/files/UIO-00005-IF-CI/registry_head_15_Ghig99q.xlsx',
        },
      ],
      task_theme: 'имттмт',
      task_text: 'митми',
      time_created: '2025-01-20T16:27:29.184069+03:00',
      time_modified: '2025-01-20T16:27:29.184092+03:00',
      due_date: '2020-10-10',
      status: 'open',
    },
    {
      id: 31,
      interface: {
        id: 143411,
        code: 'UIO-00005-IF-CI',
      },
      created_by: {
        id: 3,
        username: 'pek',
        first_name: 'Pe',
        last_name: 'K',
        email: 'pek@pesco.energy',
      },
      updated_by: null,
      reviewers: [
        {
          id: 2887,
          name: 'PEKCO',
          company_code: 'PKC',
          participation_type: 'PMC',
        },
      ],
      answers: [
        {
          id: 29,
          text: 'павпа',
          time_created: '2025-01-20T16:24:26.623388+03:00',
          task: 31,
          created_by: 3,
        },
        {
          id: 30,
          text: 'впавп',
          time_created: '2025-01-20T16:26:03.069401+03:00',
          task: 31,
          created_by: 3,
        },
      ],
      files: [
        {
          file: 'http://dcmsportal.pesco.energy/media/files/UIO-00005-IF-CI/registry_head_15.xlsx',
        },
      ],
      task_theme: 'апвапв',
      task_text: 'вапвап',
      time_created: '2025-01-20T16:24:16.537995+03:00',
      time_modified: '2025-01-20T16:24:16.538019+03:00',
      due_date: '2024-01-07',
      status: 'open',
    },
  ],
}
export const responsibleCompaniesForInterfaceTasks = {
  count: 3,
  next: null,
  previous: null,
  results: [
    {
      id: 10,
      users: [
        {
          id: 52,
          username: 'test_user',
          first_name: 'Test',
          last_name: 'User',
          email: 'test_user@pesco.ai',
        },
        {
          id: 51,
          username: 'head_user',
          first_name: 'Head',
          last_name: 'User',
          email: 'head_user@pesco.energy',
        },
        {
          id: 32,
          username: 'strange_user',
          first_name: 'Strange',
          last_name: 'User',
          email: 'strange_user@pesco.ai',
        },
      ],
      head_user: [],
      directum_id: null,
      name: 'Company full name',
      project_code: 'GCC',
      company_code: 'CODE',
      date_created: null,
      remarks: null,
      logo: '',
      participation_type: 1,
      group: null,
    },
    {
      id: 89668,
      users: [],
      head_user: [],
      directum_id: null,
      name: 'Second company full name',
      project_code: 'GCC',
      company_code: 'SCF',
      date_created: '2024-12-26T10:34:36.085100+03:00',
      remarks: null,
      logo: null,
      participation_type: 4,
      group: null,
    },
    {
      id: 657,
      users: [
        {
          id: 15,
          username: 'not_staff',
          first_name: 'Pe',
          last_name: 'Ka',
          email: 'not_staff@pesco.ai',
        },
      ],
      head_user: [
        {
          id: 13,
          username: 'not_staff',
          first_name: 'Pe',
          last_name: 'Ka',
          email: 'not_staff@pesco.ai',
        },
      ],
      directum_id: 657,
      name: 'Third company',
      project_code: 'GCC',
      company_code: 'PSV',
      date_created: null,
      remarks: 'n/a',
      logo: null,
      participation_type: null,
      group: 1,
    },
  ],
}
export const workflowAlertDeltaDays = {
  id: 1,
  description: 'l.,kmhjghngbf',
  active: true,
  code: 'workflow_alert_delta_days',
  value: '5',
  base_class: 'engineering',
  project: 'GCC',
}

export const participationTypes = [
  {
    id: 1,
    name: 'Customer',
  },
  {
    id: 2,
    name: 'PMC',
  },
  {
    id: 3,
    name: 'Contractor',
  },
  {
    id: 4,
    name: 'Subcontractor',
  },
]
export const notifications = {
  count: 106,
  results: [
    {
      id: 109,
      name: 'Notif09164',
      start_date: '2025-01-28',
      finish_date: '2025-01-28',
      companies: ['CC7'],
      participation_types: [],
      status_code: 'RLM',
      sub_class: 'BD',
      subclass_elements: [],
      responsible_engineer: 'Aleksey Evteev',
      approving_supervisor: 'Aleksey Evteev',
      engineers: ['Aleksey Evteev', 'Aleksandr Kubkin', 'Aleksander K*****'],
      watchers: [],
      disciplines: ['BL'],
      assets: ['12442'],
      document_types: [],
      creation_date: '2025-01-28T15:27:28.250498+03:00',
    },
    {
      id: 106,
      name: 'вйцй',
      start_date: '2025-01-01',
      finish_date: '2025-01-09',
      companies: ['LGN', 'NAG'],
      participation_types: ['CM'],
      status_code: 'RLM',
      sub_class: 'BD',
      subclass_elements: [null, null, null, null],
      responsible_engineer: 'Test Testov',
      approving_supervisor: 'Test Testov',
      engineers: ['Lyudmila Vishnyakova', 'Test Testov'],
      watchers: ['Test Testov', 'Петр Петров'],
      disciplines: ['3D'],
      assets: ['12442'],
      document_types: ['AGR'],
      creation_date: '2025-01-27T15:28:27.818846+03:00',
    },
    {
      id: 105,
      name: 'guweugv2ewhu2ev',
      start_date: null,
      finish_date: null,
      companies: [],
      participation_types: [],
      status_code: 'TBU',
      sub_class: null,
      subclass_elements: [],
      responsible_engineer: 'Петр Петров',
      approving_supervisor: null,
      engineers: ['Lyudmila Vishnyakova'],
      watchers: [],
      disciplines: [],
      assets: [],
      document_types: [],
      creation_date: '2025-01-21T10:32:03.780375+03:00',
    },
    {
      id: 104,
      name: 'Notification-1',
      start_date: null,
      finish_date: null,
      companies: [],
      participation_types: [],
      status_code: 'FI',
      sub_class: null,
      subclass_elements: [],
      responsible_engineer: 'Петр Петров',
      approving_supervisor: null,
      engineers: ['Lyudmila Vishnyakova'],
      watchers: [],
      disciplines: [],
      assets: [],
      document_types: [],
      creation_date: '2025-01-21T10:25:26.036470+03:00',
    },
    {
      id: 103,
      name: 'qwefqewef',
      start_date: '2025-01-25',
      finish_date: '2025-01-31',
      companies: [],
      participation_types: [],
      status_code: 'TBU',
      sub_class: null,
      subclass_elements: [],
      responsible_engineer: 'Петр Петров',
      approving_supervisor: null,
      engineers: ['Петр Петров', 'Иван Иванов'],
      watchers: [],
      disciplines: [],
      assets: [],
      document_types: [],
      creation_date: '2025-01-16T17:19:56.471158+03:00',
    },
    {
      id: 102,
      name: 'dqwdqw',
      start_date: '2025-01-17',
      finish_date: '2025-01-17',
      companies: [],
      participation_types: [],
      status_code: 'TBU',
      sub_class: null,
      subclass_elements: [],
      responsible_engineer: 'Test Testov',
      approving_supervisor: null,
      engineers: ['Lyudmila Vishnyakova', 'Test Testov'],
      watchers: [],
      disciplines: [],
      assets: [],
      document_types: [],
      creation_date: '2025-01-16T17:18:37.128353+03:00',
    },
    {
      id: 101,
      name: 'deqwcwvrevrvr3',
      start_date: null,
      finish_date: null,
      companies: [],
      participation_types: [],
      status_code: 'RLM',
      sub_class: null,
      subclass_elements: [],
      responsible_engineer: 'Lyudmila Vishnyakova',
      approving_supervisor: null,
      engineers: ['Test Testov', 'Петр Петров'],
      watchers: [],
      disciplines: [],
      assets: [],
      document_types: [],
      creation_date: '2025-01-14T17:01:08.437903+03:00',
    },
    {
      id: 100,
      name: 'dqscwdcervr',
      start_date: null,
      finish_date: null,
      companies: [],
      participation_types: [],
      status_code: 'IFA',
      sub_class: null,
      subclass_elements: [],
      responsible_engineer: 'Test Testov',
      approving_supervisor: null,
      engineers: ['Lyudmila Vishnyakova', 'Петр Петров'],
      watchers: [],
      disciplines: [],
      assets: [],
      document_types: [],
      creation_date: '2025-01-14T17:00:10.788213+03:00',
    },
    {
      id: 99,
      name: 'deqdeqwcew',
      start_date: null,
      finish_date: null,
      companies: [],
      participation_types: [],
      status_code: 'FDC',
      sub_class: null,
      subclass_elements: [],
      responsible_engineer: 'Петр Петров',
      approving_supervisor: null,
      engineers: ['Lyudmila Vishnyakova', 'Test Testov'],
      watchers: [],
      disciplines: [],
      assets: [],
      document_types: [],
      creation_date: '2025-01-14T16:59:45.815962+03:00',
    },
    {
      id: 98,
      name: 'berbrtntynbev',
      start_date: null,
      finish_date: null,
      companies: [],
      participation_types: [],
      status_code: 'IFA',
      sub_class: null,
      subclass_elements: [],
      responsible_engineer: 'Иван Иванов',
      approving_supervisor: null,
      engineers: ['Test Testov', 'Петр Петров'],
      watchers: [],
      disciplines: [],
      assets: [],
      document_types: [],
      creation_date: '2025-01-14T16:59:16.086598+03:00',
    },
  ],
}
